sudo: false

before_install:
  - gem install bundler
language: ruby
rvm:
  - 2.4.1
  - jruby-9.0.0.0
  - jruby-head
jdk:
  - oraclejdk8

  allow_failures:
    - rvm: jruby-head
notifications:
  irc: 'irc.freenode.org#awestruct'
